[refactor]  Minors numeric improvements
esa/nanosat-mo-framework pull request #121
Opened 2021-10-15 15:44 UTC by arturobernalg

* Simplify pointless arithmetic expression.
* Integer multiplication  cast to long.
* Use valueOf
* Simplify pointless arithmetic expression.

2021-11-09 17:00 UTC, arturobernalg commented
> @arturobernalg see this comment [#118 (comment)](https://github.com/esa/nanosat-mo-framework/pull/118#issuecomment-951703698)
Hi @TanguySoto 
changed.
TY

2022-06-22 15:37 UTC, dmarszk commented
I would not simplify pointless operations like 0*4, 1*4 - these are there to make the code more readable when defining a number of indexes/offsets, and the compiler optimises it out anyway. As for other changes - they look good to me. Please rebase on top of the latest dev.

2022-06-22 19:41 UTC, arturobernalg commented
> I would not simplify pointless operations like 0_4, 1_4 - these are there to make the code more readable when defining a number of indexes/offsets, and the compiler optimises it out anyway. As for other changes - they look good to me. Please rebase on top of the latest dev.

Ok, I already rebase from master and revert the pointless simplifications.

2022-06-29 08:34 UTC, dmarszk requested changes

2022-06-29 08:34 UTC, dmarszk commented on mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/CameraSoftSimAdapter.java
> +        ret[i * 3] = (byte) ((pixelval >> 16) & 0xFF); // R
Do not change this line.

2022-06-29 08:34 UTC, dmarszk commented on sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/ParameterPublishedValues.java
> +                        labels[index].setNewValue(nameId, isNotValid);
Do not change these lines.

2022-11-03 20:07 UTC, arturobernalg commented on mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/CameraSoftSimAdapter.java
> +        ret[i * 3] = (byte) ((pixelval >> 16) & 0xFF); // R
done

2022-11-03 20:07 UTC, arturobernalg commented on sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/ParameterPublishedValues.java
> +        labels[0].setNewValue("Obj Instance Id", false);
done

2022-11-03 20:07 UTC, arturobernalg commented on sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/services/mc/ParameterPublishedValues.java
> +                        labels[index].setNewValue(nameId, isNotValid);
done

2022-11-03 20:07 UTC, arturobernalg commented on mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/peripherals/PFineADCS.java
> +            public final static int MAG_FIELD_X                      = 0;
done

2023-06-21 14:30 UTC, closed without merging